environment:
  matrix:
  # node.js
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)

build_script:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run lint
